name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Capacitor CLI
      run: npm install --global @capacitor/cli

    - name: Add Android platform (si no existe)
      run: |
        if [ ! -d android ]; then
          npx cap add android
        fi

    - name: Crear carpetas faltantes para Capacitor
      run: |
        mkdir -p android/app/src/main/assets
        echo '{}' > android/app/src/main/assets/capacitor.config.json
        echo '{}' > android/app/src/main/assets/capacitor.plugins.json
        mkdir -p dist  # por si webDir apunta a dist/

    - name: Ajustar Java source a 17
      run: |
        find android -type f -name "*.gradle" -exec sed -i 's/VERSION_21/VERSION_17/g' {} \;
        find android -type f -name "*.gradle" -exec sed -i 's/--release 21/--release 17/g' {} \;

    - name: Detectar y configurar ruta correcta de Java
      run: |
        JAVA_PATH=$(dirname $(dirname $(readlink -f $(which java))))
        echo "org.gradle.java.home=$JAVA_PATH" >> android/gradle.properties

    - name: Sincronizar Capacitor
      run: npx cap sync android

    - name: Build APK Android
      working-directory: android
      run: ./gradlew assembleDebug

    - name: Subir APK compilado
      uses: actions/upload-artifact@v4
      with:
        name: avideo-app-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
