name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # versión mínima requerida para capacitor

    - name: Install dependencies
      run: npm install

    - name: Add Android platform if not exists
      run: |
        if [ ! -d "android" ]; then
          npx cap add android
        else
          echo "Android platform already exists"
        fi

    - name: Sync Android platform
      run: npx cap sync android

    - name: Build APK
      run: |
        cd android
        ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
