name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Capacitor CLI
      run: npm install --global @capacitor/cli

    - name: Add Android platform
      run: npx cap add android

    - name: Crear carpetas faltantes para Capacitor
      run: |
        mkdir -p android/app/src/main/assets
        echo '{}' > android/app/src/main/assets/capacitor.config.json
        echo '{}' > android/app/src/main/assets/capacitor.plugins.json

    - name: (Opcional) Crear carpeta dist si webDir apunta a dist/
      run: mkdir -p dist

    - name: Patch Java version in Gradle files (usar Java 17)
      run: |
        find android -type f -name "*.gradle" -exec sed -i 's/VERSION_21/VERSION_17/g' {} \;
        find android -type f -name "*.gradle" -exec sed -i 's/--release 21/--release 17/g' {} \;

    - name: Set Java 17 para Gradle
      run: echo "org.gradle.java.home=/opt/hostedtoolcache/Java_Temurin_jdk/17*/x64" >> android/gradle.properties

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Build Android APK
      working-directory: android
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: avideo-app-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
